### ISSUE TITLE
A small problem

### ISSUE THREAD

**Issue by crowforkotlin** [craterdog/java-security-framework#9]
I copied a code sample from the wiki, but the error was reported. Should I generate the public key and private key by myself?

![1654519231933](https://user-images.githubusercontent.com/60876546/172162453-8cdb0998-3288-46ab-9f32-5f5075cbdaaa.jpg)

**Comment by crowforkotlin** [comment]
PublickKey is a Interface

**Comment by crowforkotlin** [comment]
should I implements it？

**Comment by derknorton** [comment]
Thanks for reporting this, I will take a look at it and get back soon...

**Comment by derknorton** [comment]
The "val" keyword in java requires an initialization value.  Take a look at the example code test file here:
https://github.com/craterdog/java-security-framework/blob/6747200197549ccb7d24d848750d15d8946b4829/java-secure-messaging-providers/src/test/java/craterdog/security/ExampleCodeTest.java#L66

You will need to initialize the cryptex, generate a new key pair, and then retrieve the public and private keys.

Hope this helps.

**Comment by crowforkotlin** [comment]
Emm.... My language is kotlin

**Comment by derknorton** [comment]
It still requires an initialization value when you specify "val".  You are telling the compiler that this variable has a value.

**Comment by UnknowPointError** [comment]
我疑惑的是encryptSharedKey()这个函数的第一个参数PublisKey要我自己生成吗？我看Wiki 代码实例是PublikKey senderPublickKet对应的这一个参数也是一个尚未初始化的对象，是如何作为参数传递进去的？代码模板描述感觉不太清楚，有可能是我的水平太低了吧...

**Comment by crowforkotlin** [comment]
I wonder if the first parameter publiskey of the encryptsharedkey() function should be generated by me? In my opinion, the wiki code example is publickey senderpublickket. The corresponding parameter is also an object that has not been initialized. How is it passed in as a parameter? The code template description is not very clear. Maybe my level is too low

**Comment by crowforkotlin** [comment]
![image](https://user-images.githubusercontent.com/60876546/172193761-6d2879b2-abb0-4269-b1f2-2f7a20b24acf.png)
Senderpublishkey has not been initialized. How is it passed as a function parameter? Does the compiler report an error

**Comment by crowforkotlin** [comment]
I'm very sorry. I asked a stupid question. I know RSA for the first time I'm very sorry. I found that this one had to be generated by myself. I'm very sorry!!!

**Comment by derknorton** [comment]
Please look at the test code at the link I included in my previous response.  That code shows you how to generate all the keys in the example.

**Comment by crowforkotlin** [comment]
Link viewed! Thank you.
![image](https://user-images.githubusercontent.com/60876546/172378316-62bf57eb-e331-487b-833e-b3bd2c1342f3.png)
How to close the output of Java security framework on the console
